version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
cache: src/packages
branches:
  only:
    - master
before_build:
- dotnet restore Rice.SDK/Rice.SDK/Rice.SDK.sln

build:
  parallel: true
  project: Rice.SDK/Rice.SDK/Rice.SDK.sln
  verbosity: minimal

after_build:
- dotnet pack Rice.SDK/Rice.SDK/Rice.SDK.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%

test: off
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
  - path: '**\Rice.SDK.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: Qd/ycXiYXQlCudlbHPVMHn+KN45QWv3i9aINrgKI+bhpjOGvyH6EvvAj3wyzMMa5
  skip_symbols: true